//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Reportes.HistoriasClinicas {
    
    public partial class DocumentosAPacientesReporte : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "WebApp.Reportes.HistoriasClinicas.DocumentosAPacientesReporte.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
            this.SubBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("SubBand1");
            this.SubBand2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("SubBand2");
            this.SubBand3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("SubBand3");
            this.SubBand4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("SubBand4");
            this.OrdenesMedicamentosSubReporte = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRSubreport>("OrdenesMedicamentosSubReporte");
            this.OrdenesMedicamentosSubReporte.ReportSource = new WebApp.Reportes.OrdenesMedicamentos.OrdenesMedicamentosReporte();
            this.OrdenesServiciosSubReporte = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRSubreport>("OrdenesServiciosSubReporte");
            this.OrdenesServiciosSubReporte.ReportSource = new WebApp.Reportes.OrdenesMedicamentos.OrdenesMedicamentosReporte();
            this.IndicacionesMedicasSubReporte = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRSubreport>("IndicacionesMedicasSubReporte");
            this.IndicacionesMedicasSubReporte.ReportSource = new WebApp.Reportes.IndicacionesMedicas.IndicacionesMedicasReporte();
            this.IncapacidadesSubReporte = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRSubreport>("IncapacidadesSubReporte");
            this.IncapacidadesSubReporte.ReportSource = new WebApp.Reportes.Incapacidades.IncapacidadesReporte();

            // Parameters
            this.P_Ids = reportInitializer.GetParameter("P_Ids");

            // Data Sources
            this.FuenteDatos = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("FuenteDatos");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.SubBand SubBand1;
        private DevExpress.XtraReports.UI.SubBand SubBand2;
        private DevExpress.XtraReports.UI.SubBand SubBand3;
        private DevExpress.XtraReports.UI.SubBand SubBand4;
        private DevExpress.XtraReports.UI.XRSubreport OrdenesMedicamentosSubReporte;
        private DevExpress.XtraReports.UI.XRSubreport OrdenesServiciosSubReporte;
        private DevExpress.XtraReports.UI.XRSubreport IndicacionesMedicasSubReporte;
        private DevExpress.XtraReports.UI.XRSubreport IncapacidadesSubReporte;
        private DevExpress.DataAccess.Sql.SqlDataSource FuenteDatos;
        private DevExpress.XtraReports.Parameters.Parameter P_Ids;
    }
}
